baseURL = "https://caelestis-lumina.github.io/"
languageCode = "zh-cn"
title = "Caelestis Lumina"
theme = "PaperMod"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
column = "columns"

[params]
author = "Caelestis-Lumina"
description = "分享编程语言、人工智能、机器人等相关技术栈"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowToc = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowWordCount = true
DateFormat = "2006-01-02"

[params.homeInfoParams]
Title = "Welcome to CL's Blog"
Content = "这里记录 Programming Language、AI、Robotics 等技术学习与实践。"

[[menu.main]]
identifier = "posts"
name = "Articles"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "columns"
name = "Categories"
url = "/columns/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
